// <auto-generated />
using System;
using CourseFinalyProject.DataAccess.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseFinalyProject.DataAccess.Migrations
{
    [DbContext(typeof(CourseFinalyProjectContext))]
    partial class CourseFinalyProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserOpertaionClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserOpertaionClaims");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.AcademicDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrancName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DiplomaDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiplomaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inventions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AcademicDegrees");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Attestation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocDade")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiveID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("GiveID");

                    b.ToTable("Attestations");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Awards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardasDocNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AwardsDocDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AwardsTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DontSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DontSubmitNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("GiveID")
                        .HasColumnType("int");

                    b.Property<int?>("HonoraryTitleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBasis")
                        .HasColumnType("bit");

                    b.Property<string>("Mains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedalTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.AwardsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardsTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AwardsTypes");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.CombatOperations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Injury")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Territory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeteranCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VeteranCardStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.ToTable("CombatOperations");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Conscriptio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MilitaryOathTakingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentID");

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.ToTable("Conscriptio");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Departament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartamentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Departaments");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.DiscountedService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Coefficent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MilitaryServisID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MilitaryServisID")
                        .IsUnique();

                    b.ToTable("DiscountedServices");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeDocumentId");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.DodtGoAbroad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocDade")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GiveID")
                        .HasColumnType("int");

                    b.Property<bool>("IsBusinnessTrip")
                        .HasColumnType("bit");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.ToTable("DodtGoAbroads");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DiplomaDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiplomaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationTypeID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacultyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ipecialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMilitary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EducationTypeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.EducationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationTypes");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.EmployeeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DocDade")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<int>("GiveID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeDocuments");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.EmployeeFamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("FIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstNameOld")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RelativeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.ToTable("EmployeeFamilyMembers");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.EmployeeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodID")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BloodID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("EmployeeInfo");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.ExtenstionOFServiceLife", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocDade")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GiveID")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ExtenstionOFServiceLives");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.ForignLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dageer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GiveId")
                        .HasColumnType("int");

                    b.Property<bool>("IsIndefinitely")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ForignLanguages");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.FrutherEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DiplomaDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiplomaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCourse")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.ToTable("FrutherEducations");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Give", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gives");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.HonoraryTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HonoraryTitleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HonoraryTitles");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.LaborActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrganizationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LaborActivity");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.MHHK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MHHKDocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MHHKDocNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("MHHKs");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.MHHKType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MHHKTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MHHKTypes");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.MedalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAll")
                        .HasColumnType("bit");

                    b.Property<string>("MedalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedalTypes");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.MilitaryRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("GiveId")
                        .HasColumnType("int");

                    b.Property<int>("RankID")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MilitaryRanks");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.MilitaryService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId1")
                        .HasColumnType("int");

                    b.Property<string>("Departament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocDade")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GiveID")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId1");

                    b.ToTable("MilitaryServices");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.RankStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RankStatuses");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.RankType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NextTimeRank")
                        .HasColumnType("int");

                    b.Property<string>("RankGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RankTypes");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.RelativeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RelativeTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RelativeTypes");
                });

            modelBuilder.Entity("EmployeeExtenstionOFServiceLife", b =>
                {
                    b.Property<int>("EmployeesId")
                        .HasColumnType("int");

                    b.Property<int>("ExtenstionOFServiceLivesId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesId", "ExtenstionOFServiceLivesId");

                    b.HasIndex("ExtenstionOFServiceLivesId");

                    b.ToTable("EmployeeExtenstionOFServiceLife");
                });

            modelBuilder.Entity("EmployeeMilitaryRank", b =>
                {
                    b.Property<int>("EmployeesId")
                        .HasColumnType("int");

                    b.Property<int>("MilitaryRanksId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesId", "MilitaryRanksId");

                    b.HasIndex("MilitaryRanksId");

                    b.ToTable("EmployeeMilitaryRank");
                });

            modelBuilder.Entity("EmployeeMilitaryService", b =>
                {
                    b.Property<int>("EmployeesId")
                        .HasColumnType("int");

                    b.Property<int>("MilitaryServicesId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesId", "MilitaryServicesId");

                    b.HasIndex("MilitaryServicesId");

                    b.ToTable("EmployeeMilitaryService");
                });

            modelBuilder.Entity("MilitaryRankRankStatus", b =>
                {
                    b.Property<int>("MilitaryRanksId")
                        .HasColumnType("int");

                    b.Property<int>("RankStatusesId")
                        .HasColumnType("int");

                    b.HasKey("MilitaryRanksId", "RankStatusesId");

                    b.HasIndex("RankStatusesId");

                    b.ToTable("MilitaryRankRankStatus");
                });

            modelBuilder.Entity("MilitaryRankRankType", b =>
                {
                    b.Property<int>("MilitaryRanksId")
                        .HasColumnType("int");

                    b.Property<int>("RankTypesId")
                        .HasColumnType("int");

                    b.HasKey("MilitaryRanksId", "RankTypesId");

                    b.HasIndex("RankTypesId");

                    b.ToTable("MilitaryRankRankType");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.AcademicDegree", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", "Employee")
                        .WithMany("AcademicDegrees")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Attestation", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", "Employee")
                        .WithMany("Attestations")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFinalyProject.Entities.Concrete.Give", "Give")
                        .WithMany()
                        .HasForeignKey("GiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Give");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Awards", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", null)
                        .WithMany("Awardses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.CombatOperations", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", "Employee")
                        .WithMany("CombatOperations")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Conscriptio", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", "Employee")
                        .WithOne("Conscriptio")
                        .HasForeignKey("CourseFinalyProject.Entities.Concrete.Conscriptio", "EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departament");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.DiscountedService", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.MilitaryService", "MilitaryService")
                        .WithOne("DiscountedService")
                        .HasForeignKey("CourseFinalyProject.Entities.Concrete.DiscountedService", "MilitaryServisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MilitaryService");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.DocumentType", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.EmployeeDocument", null)
                        .WithMany("DocumentTypes")
                        .HasForeignKey("EmployeeDocumentId");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.DodtGoAbroad", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", null)
                        .WithMany("DodtGoAbroads")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Education", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.EducationType", "EducationType")
                        .WithMany()
                        .HasForeignKey("EducationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", "Employee")
                        .WithMany("Educations")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.EmployeeFamilyMember", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", null)
                        .WithMany("EmployeeFamilyMembers")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.EmployeeInfo", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.BloodType", "BloodType")
                        .WithMany("EmployeeInfos")
                        .HasForeignKey("BloodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.ForignLanguage", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", null)
                        .WithMany("ForignLanguages")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.FrutherEducation", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", "Employee")
                        .WithMany("FrutherEducations")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.LaborActivity", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", null)
                        .WithMany("laborActivities")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.MHHK", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", null)
                        .WithMany("MHHKs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.MilitaryService", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Branch", null)
                        .WithMany("MilitaryServices")
                        .HasForeignKey("BranchId1");
                });

            modelBuilder.Entity("EmployeeExtenstionOFServiceLife", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFinalyProject.Entities.Concrete.ExtenstionOFServiceLife", null)
                        .WithMany()
                        .HasForeignKey("ExtenstionOFServiceLivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeMilitaryRank", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFinalyProject.Entities.Concrete.MilitaryRank", null)
                        .WithMany()
                        .HasForeignKey("MilitaryRanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeMilitaryService", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFinalyProject.Entities.Concrete.MilitaryService", null)
                        .WithMany()
                        .HasForeignKey("MilitaryServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryRankRankStatus", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.MilitaryRank", null)
                        .WithMany()
                        .HasForeignKey("MilitaryRanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFinalyProject.Entities.Concrete.RankStatus", null)
                        .WithMany()
                        .HasForeignKey("RankStatusesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryRankRankType", b =>
                {
                    b.HasOne("CourseFinalyProject.Entities.Concrete.MilitaryRank", null)
                        .WithMany()
                        .HasForeignKey("MilitaryRanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFinalyProject.Entities.Concrete.RankType", null)
                        .WithMany()
                        .HasForeignKey("RankTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.BloodType", b =>
                {
                    b.Navigation("EmployeeInfos");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Branch", b =>
                {
                    b.Navigation("MilitaryServices");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.Employee", b =>
                {
                    b.Navigation("AcademicDegrees");

                    b.Navigation("Attestations");

                    b.Navigation("Awardses");

                    b.Navigation("CombatOperations");

                    b.Navigation("Conscriptio")
                        .IsRequired();

                    b.Navigation("DodtGoAbroads");

                    b.Navigation("Educations");

                    b.Navigation("EmployeeFamilyMembers");

                    b.Navigation("ForignLanguages");

                    b.Navigation("FrutherEducations");

                    b.Navigation("MHHKs");

                    b.Navigation("laborActivities");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.EmployeeDocument", b =>
                {
                    b.Navigation("DocumentTypes");
                });

            modelBuilder.Entity("CourseFinalyProject.Entities.Concrete.MilitaryService", b =>
                {
                    b.Navigation("DiscountedService")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
